spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://70.12.246.40:3306/webproject?serverTimezone=UTC
    url: jdbc:mysql://54.180.9.92:3306/wineproject?serverTimezone=UTC
    username: test
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update    
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: exception
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafytest@gmail.com
    password: 1q2w!@QW
    properties:      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true      
server:
  servlet:
    context-path: /WineProject
  port: 8090
logging:
  level:
    com:
      andy: trace